### ISSUE TITLE
Become a mouse driver instead

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/cycle-mouse-driver#1]
It would be great to have streams for `mouseup`, `mousedown` and `click` for the whole document. It can be useful in some components who want to know about mouse events in the outside world.

**Comment by artfuldev** [comment]
We could start with renaming the repo to `cycle-mouse` or similar. And then transfer it to cyclejs-community where more of us can collaborate on this. :)

**Comment by raquelxmoss** [comment]
So, I need to update this driver so that I can finally release [Cycle Color Picker](https://github.com/raquelxmoss/cycle-color-picker)  (this is driving me nuts, I just want to release it!).

My plan:
- Rename repo
- Convert to xstream
- Add mouseup, mousedown, and click events
- Update readme with examples for new methods
- Release on npm (breaking change)

Later on we can look at issues #4, #6, and adding all events listed in #3. Basically I'd just like to get the list above done so that I can free up my time and brainspace for working on this and the keyboard driver. 

I will need help with the fiddly bits of releasing on npm, hopefully from @Widdershin because you can sit next to me while I'm doing it 😛 . Later on, help with typescript stuff will be appreciated @artfuldev. I have some thoughts on that which I'll write out on the issue a bit later.

**Comment by raquelxmoss** [comment]
I have changed this to be Cycle Mouse Driver on Github, and added `up()`, `down()`, `click()` methods. I've updated the readme and example, and published this to npm as `cycle-mouse-driver` https://www.npmjs.com/package/cycle-mouse-driver

It's not perfect, but it's a start!
