### ISSUE TITLE
Is cycle-mouse taken?

### ISSUE THREAD

**Issue by artfuldev** [cyclejs-community/cycle-mouse-driver#9]
`cycle-mouse` sounds better than `cycle-mouse-driver` to me, and is also in line with other drivers like `cycle dom` and `cycle http` :)

Your thoughts, please?

**Comment by raquelxmoss** [comment]
I like `cycle-mouse-driver` myself, as it is nice and searchable and very clear. I did that with beginners and people new to the community in mind, kind of a 'does what it says on the label' mentality. As it's not part of the cycle core, I don't think it should have to use the same naming as `cycle-dom` or `cycle-http`. 

I'm open to more opinions on this! In a minute I'm going to add a Suggestions/Feedback section to the readme, and open a general issue for suggestions and feedback, so that community members know that they can post there.
